[package]
name = "tracea-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "tracea"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.0", features = ["extension-module"] }
tracea = { path = "../" }
